export enum FailureType {
  NONE = "NONE",

  BACKEND_PRICING = "BACKEND_PRICING",
  BACKEND_TIMEOUT = "BACKEND_TIMEOUT",
  BACKEND_UNKNOWN = "BACKEND_UNKNOWN",

  LLM_BEHAVIOR = "LLM_BEHAVIOR",

  CAPABILITY_GAP_DELIVERY = "CAPABILITY_GAP_DELIVERY",
  CAPABILITY_GAP_ITEM = "CAPABILITY_GAP_ITEM",

  STAGNATION = "STAGNATION",

  FAILED = "FAILED"
}